services:

  dev:
    build: .
    command: sleep infinity
    volumes:
      - ../.:/workspace
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql://root@database:3306/histotrip?serverVersion=8.2.0&charset=utf8mb4"
      MAILER_DSN: "smtp://mailer:1025"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  
  database:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - 8081:80
    environment:
      PMA_HOST: database

volumes:
  db-data: