services:

  dev:
    build: .
    command: sleep infinity
    volumes:
      - ../.:/workspace
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/app.db"
      MAILER_DSN: "smtp://mailer:1025"

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
